apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/priestjim/kube2iam//kustomize/base

commonLabels:
  app.kubernetes.io/name: kube2iam

images:
- name: priestjim/kube2iam
  newTag: 0.10.6

namespace: kube2iam

patchesStrategicMerge:
- daemonset.yaml

resources:
- podsecuritypolicy.yaml
