name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  kubeval-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.19.1
      - name: Run kubeval
        run: |
          KUBERNETES_VERSION=${{ matrix.k8s }}
          .github/workflows/kubeval.sh
    strategy:
      matrix:
        k8s:
          - 1.31
          - 1.32
          - 1.33
          - 1.34
